language: java

env:
  global:
  - secure: wr9zKPOtOS6P0lKfGISYwgMdEbsBjC0adxYZZ6xi8Z//B4PXnvaYDg2Vxk2PQ0wcMBV9Cl4Lj6Be34lIbDfxTkkMQiZY/3t6BxzjyTay1CquqoLenP6j/2PmltMIJGMVb/02eSUdRgeGbeiOHNEnylHnQ+9cWdSE6jq4nGT2Hbk=
  - secure: Q3Rja+G/aV8h7Vvnz+AW2bsR6rn6vZbowmw57Psk95WWkFEigSqWFkG3PE4VYo1/Ib2vuktPTuPadonDgZ55I2XYZ2C1WCoJCO+1mErQiEHKdaWglccbmE3k+JJQkfwGuhkAx/ucki+j6o0giykH+EAtilKfQWQWwoFhYunzXqo=

after_success:
- gradle bintrayUpload -PbintrayUser="${BINTRAY_USER}" -PbintrayKey="${BINTRAY_KEY}"
