language: java
env:
  global:
  - secure: h1VoF715l5ekQ5TJTadG1P7rQtvkDbxLS1IDgCPrSqs0JZ25SbtdXfrwD/P3m9+Fsb0OoQBWKKFa4BGRiyPUpYvB7ma2X4o6tkWuIOi7lXX+R8cV9szcq7grDrdZdUFj32lmn7RBKIomoOLx/yeol5JKCdBRg2Lm1XOykAIb1iQ=
  - secure: QC5vMWqKrqXYs10meOzuOFs6P2u0LNGRBt2Ca6lal9SICWXF4XkmPwWhzRGUDO6QUP4D8qE40ZU/0FFNWvwdLIB+7Se+k27Lt80FOtgB66RmDAiptzan8Mwwq7w5lqdxE1oRfmB0pUVv06M/RDI3NYqHSBouPIiT7AB5BfmgSIg=

after_success:
	- gradle bintrayUpload